### ISSUE TITLE
Get it to work with Goots!

### ISSUE THREAD

**Issue by aubreypwd** [aubreypwd/wp-noteup#73]
See [https://wordpress.org/support/topic/integration-with-the-gutenberg-editor/](https://wordpress.org/support/topic/integration-with-the-gutenberg-editor/)

**Comment by danieljwonder** [comment]
Tried this plugin on a site and it appears within Gutenberg but doesn't appear to actually save anything.

Any ETA on support or recommended alternatives?

**Comment by aubreypwd** [comment]
Just tried this in 5.1.1 and it seems to be working (e.g. adding media to the Notes section). Please let me know if this is still the case for you.

**Comment by aubreypwd** [comment]
Will work in upcoming 1.3 release on WordPress 5.2.1
